//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PinchukovLobutev9_14.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Authorization
    {
        public int ID { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public Nullable<int> IdClient { get; set; }
        public Nullable<int> IdEmployee { get; set; }
    
        public virtual Client1 Client1 { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
