//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PinchukovLobutev9_14.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderStatic
    {
        public int ID { get; set; }
        public int IdClient { get; set; }
        public int IdEmployee { get; set; }
        public System.DateTime Date { get; set; }
        public string NameOfProduct { get; set; }
        public byte[] ImageProduct { get; set; }
        public short Quantity { get; set; }
        public Nullable<decimal> FullPrice { get; set; }
        public decimal Price { get; set; }
    }
}
